version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-pages
          command: cat publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: prashant-shahi/charts
      - run:
          name: Verify
          command: |
            alias helm=/tmp/helm/bin/linux-amd64/helm
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              helm repo add dgraph https://prashant-shahi.github.io/charts
              helm repo update
              helm repo list
              helm inspect dgraph/dgraph
            fi
